//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendrixAccountant.Data.HendrixContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOGOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATALOGOS()
        {
            this.ITEM_CATALOGO = new HashSet<ITEM_CATALOGO>();
        }
    
        public int id_catalogo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int tipo { get; set; }
        public bool estado { get; set; }
        public System.DateTime creado_en { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> modificado_en { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> eliminado_en { get; set; }
        public string usuario_elim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_CATALOGO> ITEM_CATALOGO { get; set; }
    }
}
