//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendrixAccountant.Data.HendrixContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int id_cliente { get; set; }
        public string identificacion { get; set; }
        public string tipo_identificacion { get; set; }
        public string tipo_cliente { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public bool estado { get; set; }
        public string usuario_crea { get; set; }
        public System.DateTime creado_en { get; set; }
        public string usuario_mod { get; set; }
        public Nullable<System.DateTime> modificado_en { get; set; }
        public string usuario_elim { get; set; }
        public Nullable<System.DateTime> eliminado_en { get; set; }
    }
}
