//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendrixAccountant.Data.HendrixContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADAS_DETALLE
    {
        public int id_entrada_detalle { get; set; }
        public Nullable<int> entrada_id { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<int> stock_actual { get; set; }
        public Nullable<int> stock_nuevo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual ENTRADAS ENTRADAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
