//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendrixAccountant.Data.HendrixContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTRADAS()
        {
            this.ENTRADAS_DETALLE = new HashSet<ENTRADAS_DETALLE>();
        }
    
        public int id_entrada { get; set; }
        public System.DateTime fecha_emision { get; set; }
        public string num_comprobante { get; set; }
        public Nullable<int> tipo_comprobante { get; set; }
        public Nullable<int> proveedor_id { get; set; }
        public string observaciones { get; set; }
        public decimal total_compra { get; set; }
        public bool estado { get; set; }
        public System.DateTime creado_en { get; set; }
        public string usuario_crea { get; set; }
        public Nullable<System.DateTime> modificado_en { get; set; }
        public string usuario_modifica { get; set; }
        public Nullable<System.DateTime> eliminado_en { get; set; }
        public string usuario_elimina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADAS_DETALLE> ENTRADAS_DETALLE { get; set; }
    }
}
