//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendrixAccountant.Data.HendrixContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_CAJA
    {
        public int id_movimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<short> tipo_movimiento { get; set; }
        public Nullable<decimal> ingresos { get; set; }
        public Nullable<decimal> egresos { get; set; }
        public Nullable<decimal> saldo { get; set; }
        public int usuario_id { get; set; }
        public int caja_id { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual CAJA CAJA { get; set; }
    }
}
